KaiutYoga/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaiutYoga.Models;

namespace KaiutYoga.Controllers
{
    [Authorize]
    public class PlanController : Controller
    {
        private KaiutYogaContext db = new KaiutYogaContext();

        //
        // GET: /Plan/

        public ActionResult Index()
        {
            return View(db.PlanModels.ToList().OrderBy(c => c.Name));
        }

        //
        // GET: /Plan/Details/5

        public ActionResult Details(long id = 0)
        {
            PlanModel planmodel = db.PlanModels.Find(id);
            if (planmodel == null)
            {
                return HttpNotFound();
            }
            return View(planmodel);
        }

        //
        // GET: /Plan/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Plan/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlanModel planmodel)
        {
            if (ModelState.IsValid)
            {
                db.PlanModels.Add(planmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(planmodel);
        }

        //
        // GET: /Plan/Edit/5

        public ActionResult Edit(long id = 0)
        {
            PlanModel planmodel = db.PlanModels.Find(id);
            if (planmodel == null)
            {
                return HttpNotFound();
            }
            return View(planmodel);
        }

        //
        // POST: /Plan/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlanModel planmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(planmodel);
        }

        //
        // GET: /Plan/Delete/5

        public ActionResult Delete(long id = 0)
        {
            PlanModel planmodel = db.PlanModels.Find(id);
            if (planmodel == null)
            {
                return HttpNotFound();
            }
            return View(planmodel);
        }

        //
        // POST: /Plan/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                PlanModel planmodel = db.PlanModels.Find(id);
                db.PlanModels.Remove(planmodel);
                db.SaveChanges();
                ViewBag.ErrorContent = null;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorContent"] = "Houve um problema ao apagar este registro, primeiro selecione outro planos para os alunos que estao matriculados nessa frequencia.";
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

KaiutYoga/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaiutYoga.Models;
using KaiutYoga.DAL;
using PagedList;
using KaiutYoga.ViewModels;
using Newtonsoft.Json;
using System.IO;
using System.Web.UI.WebControls;
using System.Web.UI;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;

namespace KaiutYoga.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private KaiutYogaContext db = new KaiutYogaContext();

        //
        // GET: /Client/

        public ActionResult Index(string sortOrder, string currentFilter, string searchName, int? page, bool studentStatus = true)
        {
            
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "firstname_desc" : "";
            ViewBag.LastNameSortParm = sortOrder == "lastname" ? "lastname_desc" : "lastname";
            ViewBag.PlanSortParm = sortOrder == "plan" ? "plan_desc" : "plan";
            ViewBag.studentStatus = studentStatus;

            if (searchName != null)
            {
                page = 1;
            }
            else
            {
                searchName = currentFilter;
            }

            ViewBag.searchName = searchName;
            ViewBag.CurrentFilter = searchName;

            var studentmodel = db.StudentModels.Include(c => c.Classes).Include(c => c.Plan).Where(c=>c.Active == studentStatus).ToList();
            if (!String.IsNullOrEmpty(searchName))
            {
                studentmodel = studentmodel.Where(c => c.Name.ToUpper().Contains(searchName.ToUpper())).ToList();
            }

            switch (sortOrder)
            {
                case "lastname":
                    studentmodel = studentmodel.OrderBy(c => c.LastName).ToList();
                    break;
                case "lastname_desc":
                    studentmodel = studentmodel.OrderByDescending(c => c.LastName).ToList();
                    break;
                case "plan":
                    studentmodel = studentmodel.OrderBy(c => c.Plan.Name).ToList();
                    break;
                case "plan_desc":
                    studentmodel = studentmodel.OrderByDescending(c => c.Plan.Name).ToList();
                    break;
                case "firstname_desc":
                    studentmodel = studentmodel.OrderByDescending(c => c.FirstName).ToList();
                    break;
                default:
                    studentmodel = studentmodel.OrderBy(c => c.FirstName).ToList();
                    break;

            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(studentmodel.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Client/Details/5

        public ActionResult Details(long id = 0)
        {
            StudentModel StudentModel = db.StudentModels.Find(id);
            if (StudentModel == null)
            {
                return HttpNotFound();
            }            
            return View(StudentModel);
        }

        //
        // GET: /Client/Create

        public ActionResult Create()
        {
            ViewBag.PlanId = new SelectList(db.PlanModels, "Id", "Name");
            return View();
        }

        //
        // POST: /Client/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentModel StudentModel)
        {
            if (ModelState.IsValid)
            {
                ClassRepository cr = new ClassRepository(db);
                StudentModel.Classes = new List<ClassModel>();
                //StudentModel.Register = DateTime.Now;
                if (TempData["SelectedClasses"] != null)
                {
                    foreach (long classId in TempData["SelectedClasses"] as List<long>)
                    {
                        StudentModel.Classes.Add(cr.GetClass(classId));
                    }
                }
                PlanModel pm = db.PlanModels.Find(StudentModel.PlanId);
                StudentModel.ReplacamentClasses = new List<SpareClassModel>();

                if (TempData["SpareClasses"] != null){
                    foreach (SpareClassModel scm in TempData["SpareClasses"] as List<SpareClassModel>)
                    {
                        scm.IsTrial = pm.IsTrial;
                        StudentModel.ReplacamentClasses.Add(scm);
                    }
                }
                //StudentModel.ChangedPlan = DateTime.Now;
                StudentModel.RegisterDate = DateTime.Now;
                StudentModel.Active = true;
                //StudentModel.BirthDate = DateTime.Now;
                //StudentModel.Payments = new List<PaymentModel>();
                
                db.StudentModels.Add(StudentModel);
                db.SaveChanges();

                if (!pm.IsTrial)
                {
                    StudentModel.Payments = new List<PaymentModel>();
                    StudentModel.Payments.Add(new PaymentModel(StudentModel.Id, pm.Id, DateTime.Now,new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.DaysInMonth(DateTime.Now.Year,DateTime.Now.Month))));
                }

                db.Entry(StudentModel).State = EntityState.Modified;
                db.SaveChanges();


                return RedirectToAction("Index");
            }

            ViewBag.PlanId = new SelectList(db.PlanModels, "Id", "Name", StudentModel.PlanId);
            return View(StudentModel);
        }

        public ActionResult GetClassCalendar(int planId = 0, int studentId = 0)
        {
            TempData.Remove("SelectedClasses");
            TempData.Remove("SpareClasses");
            TempData.Remove("RemovedSpareClasses");

            StudentModel sm = new StudentModel();
            PlanModel pm = db.PlanModels.Where(i => i.Id == planId).Single();
            sm.PlanId = planId;
            sm.Plan = pm;
            if (studentId != 0)
            {
                List<PresenceModel> lpm = db.PresenceModels.ToList();
                sm = db.StudentModels.Include(c=>c.WeeklyPresence).Where(c => c.Id == studentId).SingleOrDefault();
                sm.PlanId = planId;
                sm.Plan = pm;

                List<long> classes = new List<long>();
                
                if (sm.Classes != null)
                {
                    foreach (ClassModel cm in sm.Classes)
                    {
                        classes.Add(cm.Id);
                    }
                    TempData["SelectedClasses"] = classes;
                }
                List<SpareClassModel> replacementclasses = new List<SpareClassModel>();
                if (sm.ReplacamentClasses != null)
                {
                    // code to ignore spare classes older than 2 months, removed because it is meesing with history
                    foreach (SpareClassModel scm in sm.ReplacamentClasses) //.Where(c=>c.NewDate >= DateTime.Now.AddMonths(-2)))
                    {
                        //if (lpm.Find(c=>c.ClassId == scm.NewClassId && c.Date == scm.NewDate) == null)
                            replacementclasses.Add(scm);
                    }
                    TempData["SpareClasses"] = replacementclasses;
                }
            }

            return PartialView("_StudentCalendar", sm);
        }

        [HttpPost]
        public string AddClass(long studentId = 0, long classId = 0, long planId = 0, long amountspare = 0, string date = "", bool onlySpare = false)
        {
            StudentModel student = new StudentModel();
            if (studentId != 0)
            {
                student = db.StudentModels.Include(c => c.EnroledWeeklyClasses)
                    .Include(c => c.EnroledReplacementClasses)
                    .Include(c => c.EnroledTrialClasses)
                    .Include(c => c.WeeklyPresence)
                    .Include(c => c.ReplacementPresence)
                    .Include(c => c.TrialPresence)
                    .Include(c => c.ReplacamentClasses)
                    .Where(c => c.Id == studentId).Single();
            }
            PlanModel pm = db.PlanModels.Find(planId);
            long frequency = pm.Frequency;
            if (pm.IsTrial)
            {
                if (studentId == 0)
                    amountspare += pm.Frequency;
                frequency = 0;
            }

            DateTime classDate = new DateTime(1970, 1, 1, 0, 0, 0, 0); //Set default date 1/1/1970
            classDate = classDate.AddMilliseconds(Convert.ToDouble(date));

            List<long> classes = new List<long>();
            List<SpareClassModel> spareclasses = new List<SpareClassModel>();
            List<SpareClassModel> removedspareclasses = new List<SpareClassModel>();

            AddClassStudent acs = new AddClassStudent();
            acs.HavePresenceList = db.ClassModels.Find(classId).HavePresenceList(date);
            
            if (TempData["SelectedClasses"] != null)
            {
                classes = TempData["SelectedClasses"] as List<long>;
                TempData.Keep("SelectedClasses");
            }

            long amountclasseswithpresencelist = 0;
            if (TempData["SpareClasses"] != null)
            {
                spareclasses = TempData["SpareClasses"] as List<SpareClassModel>;
                TempData.Keep("SpareClasses");
                if (spareclasses == null)
                    spareclasses = new List<SpareClassModel>();

                foreach (SpareClassModel scm in spareclasses)
                {
                    if (scm.PresenceList() != null)
                        amountclasseswithpresencelist++;
                }
            }

            if (TempData["RemovedSpareClasses"] != null)
            {

KaiutYoga/Views/Student/Create.cshtml
@model KaiutYoga.Models.StudentModel

@{
    KaiutYoga.Models.KaiutYogaContext context = new KaiutYoga.Models.KaiutYogaContext();
    int amountPlans = context.PlanModels.Count();
    int amountClasses = context.ClassModels.Count();

    ViewBag.Title = "Cadastro de aluno";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div class="row">
        <div class="col-md-3">
            <h3>
                Cadastrar novo aluno

            </h3>
            <div class="editor-label">
                @Html.LabelFor(model => model.FirstName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.LastName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Gender)
            </div>
            <div class="editor-field">
                @Html.EnumDropDownListFor(model => model.Gender, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BirthDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.PlanId)
            </div>
            <div class="editor-field">
                @Html.DropDownList("PlanId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PlanId, "", new { @class = "text-danger" })
            </div>

            @Html.Partial("_CalendarSubtitle")

            <input type="submit" value="Salvar" class="btn btn-primary"  onclick="changed=false"/>
            
            @Html.ActionLink("Voltar a lista de alunos", "Index", null, new { @class = "btn btn-default" })
        </div>


        <div class="col-md-9">
            <div id="tabs" style="margin-top:15px" class="row-fluid">
                <ul>
                    <li><a href="#calendar">Aulas</a></li>
                    <li><a href="#additionalInfo">Informações adicionais</a></li>
                </ul>
                <div id="calendar" class="row-fluid">
                    <h1>Selecione um plano de aula</h1>
                </div>
                <div id="additionalInfo" class="row-fluid">
                    <div class="col-md-6">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Address)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Neighborhood)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Neighborhood, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Neighborhood, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.City)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.CEP)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.RG)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.RG, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RG, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.CPF)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.MaritalStatus)
                        </div>
                        <div class="editor-field">
                            @Html.EnumDropDownListFor(model => model.MaritalStatus, null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MaritalStatus, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Occupation)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
                        </div>

                        <div class="editor-label">
                            @Html.LabelFor(model => model.Phone)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>

                        <div class="editor-label">
                            @Html.LabelFor(model => model.CelPhone)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.CelPhone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CelPhone, "", new { @class = "text-danger" })
                        </div>

                        <div class="editor-label">
                            @Html.LabelFor(model => model.Email)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>

                        <div class="editor-label">
                            @Html.LabelFor(model => model.Observations)
                        </div>
                        <div class="editor-multiline-field">
                            @Html.EditorFor(model => model.Observations, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Observations, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="errorMsgModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                
                <h4 class="modal-title">Faltam dados!</h4>
            </div>
            <div class="modal-body">
                <p>Para completar o cadastro de aluno voce ainda precisa de:</p>
                @if (amountPlans == 0)
                {
                    <ul>@Html.ActionLink("Plano de aula", "Create", "Plan", null, null)</ul>
                }
                @if (amountClasses == 0)
                {
                    <ul>@Html.ActionLink("Horários de aula", "Index", "Class", null, null)</ul>
                }
            </div>
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(document).ready(function () {
        @if (amountPlans == 0 || amountClasses == 0) { 
            <text>
            $('#errorMsgModal').modal('show');
            $('#errorMsgModal').on('hide.bs.modal', function(e) { return false; })
            </text>
        }
    })
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $("*").on("input", function () {
        changed = true;
    });

    $('#PlanId').change(function () {
        /* Get the selected value of dropdownlist */
        var selectedID = $(this).val();
        /* Request the partial view with .get request. */
        if (selectedID != "") {
            $.ajax({
                type: 'post',
                url: window.applicationBaseUrl + "Student/GetClassCalendar",
                dataType: "html",
                data: "planId=" + selectedID,
                contentType: "application/x-www-form-urlencoded;charset=utf-8",
                async: true,
                success: function (result) {
                    $('#calendar').html(result);
                }

            })
        }
        else {
            $('#calendar').html("<h1>Selecione um plano de aula</h1>");
        }
    });

    var selectedID = $("#PlanId").val();
    /* Request the partial view with .get request. */
    if (selectedID != "") {
        $.ajax({
            type: 'post',
            url: window.applicationBaseUrl + "Student/GetClassCalendar",
            dataType: "html",
            data: "planId=" + selectedID,
            contentType: "application/x-www-form-urlencoded;charset=utf-8",
            async: true,
            success: function (result) {
                $('#calendar').html(result);
            }
        })
    }

    $(window).bind('beforeunload', function () {
        if (changed) {
            //return $("#leavingPageModal").modal('show');
            return 'Você fez iniciou o cadastro deste aluno e não terminou, deseja mesmo sair?';
        }
    });

</script>

KaiutYoga/Views/Student/Delete.cshtml
@model KaiutYoga.Models.StudentModel

@{
    ViewBag.Title = "Apagar aluno";
}

<h2>Alunos</h2>

<div class="form-horizontal">
    <h4>Apagar</h4>
    <hr />
    <h3>Realmente deseja apagar este registro?</h3>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Plan.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Plan.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Apagar" class="btn btn-default" />
            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Voltar a lista de alunos", "Index")
</div>

KaiutYoga/Views/Student/Index.cshtml
@model PagedList.IPagedList<KaiutYoga.Models.StudentModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Lista de alunos";
}

<h2>Lista de alunos</h2>

<p>

</p>


<p>
    <div class="form-inline">
        <div class="form-group">

            @using (Html.BeginForm("Index", "Student", FormMethod.Get))
            {
                //@Html.TextBox("searchName", ViewBag.searchName as string, new { @class = "form-control", @placeholder = "Nome ou sobrenome"})

                @Html.TextBox("searchName", ViewBag.searchName as string, new { @class = "form-control", @placeholder = "Nome ou sobrenome", @onchange = "this.form.submit();" })

                <select onchange="this.form.submit();" id="studentStatus" name="studentStatus" class="form-control">
                    <option value="True">Ativos</option>
                    <option value="False">Inativos</option>
                </select>
                
                <button type="submit" id="btnsubmit" class="btn btn-default"><i class="fa fa-search" title="Pesquisar"></i> Pesquisar</button>
            }
        </div>

        <button class="btn btn-primary " onclick="location.href='@Url.Action("Create")'"><i class="fa fa-plus" title="Novo aluno"></i> Novo registro</button>
        <button class="btn btn-info " onclick="location.href='@Url.Action("Report")'"><i class="fa fa-archive" title="Relatórios"></i> Relatórios</button>
    </div>
</p>
<script>
    $("#studentStatus").val("@ViewBag.studentStatus");
</script>
<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>
<div id="no-more-tables">
    <table class="table col-sm-12 table-striped table-condensed cf">
        <thead class="cf">
            <tr>
                <th>
                    @Html.ActionLink("Nome", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Sobrenome", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.DisplayName("Telefone residencial")
                </th>
                <th>
                    @Html.DisplayName("Celular")
                </th>
                <th>
                    @Html.ActionLink("Plano", "Index", new { sortOrder = ViewBag.PlanSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-title="Nome">
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td data-title="Sobrenome">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td data-title="Residencial">
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td data-title="Celular">
                        @Html.DisplayFor(modelItem => item.CelPhone)
                    </td>
                    <td data-title="Plano">
                        @Html.DisplayFor(modelItem => item.Plan.Name)
                    </td>
                    <td data-title="" align="right">
                        <div class="form-inline">
                            <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete",new { id=item.Id})'"><i class="fa fa-trash" title="Apagar aluno"></i> Apagar</button>
                            <div class="form-group">
                                <button class="btn btn-warning btn-sm" onclick="location.href='@Url.Action("Edit", new { id = item.Id })'"><i class="fa fa-pencil" title="Editar aluno"></i> Editar</button>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>