KaiutYoga/KaiutYoga/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaiutYoga.Models;
using KaiutYoga.ViewModels;
using PagedList;
using Newtonsoft.Json;

namespace KaiutYoga.Controllers
{
    [Authorize]
    public class ClassController : Controller
    {
        private KaiutYogaContext db = new KaiutYogaContext();

        // GET: /CreateClass/
        public ActionResult Index(string sortOrder, string currentFilter, string searchDayOfWeek, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TimeSortParm = String.IsNullOrEmpty(sortOrder) ? "time_desc" : "";
            ViewBag.ProfessorSortParm = sortOrder == "professor" ? "professor_desc" : "professor";
            ViewBag.RoomSortParm = sortOrder == "room" ? "room_desc" : "room";
            ViewBag.DaySortParm = sortOrder == "day" ? "day_desc" : "day";

            if (searchDayOfWeek != null)
            {
                page = 1;
            }
            else
            {
                searchDayOfWeek = currentFilter;
            }

            ViewBag.CurrentFilter = searchDayOfWeek;


            var classmodel = db.ClassModels.Include(c => c.Professor).Include(c => c.Room).Where(c => c.Active).ToList();
            if (!String.IsNullOrEmpty(searchDayOfWeek))
            {
                classmodel = classmodel.Where(c => c.Day == (DayOfWeek)Enum.Parse(typeof(DayOfWeek), searchDayOfWeek, true)).ToList();// Professor.Name.Contains(searchString) || s.Room.Name.Contains(searchString)).ToList();
            }

            switch (sortOrder)
            {
                case "professor":
                    classmodel = classmodel.OrderBy(c => c.Professor.Name).ToList();
                    break;
                case "professor_desc":
                    classmodel = classmodel.OrderByDescending(c => c.Professor.Name).ToList();
                    break;
                case "room":
                    classmodel = classmodel.OrderBy(c => c.Room.Name).ToList();
                    break;
                case "room_desc":
                    classmodel = classmodel.OrderByDescending(c => c.Room.Name).ToList();
                    break;
                case "day":
                    classmodel = classmodel.OrderBy(c => c.Day).ToList();
                    break;
                case "day_desc":
                    classmodel = classmodel.OrderByDescending(c => c.Day).ToList();
                    break;
                case "time_desc":
                    classmodel = classmodel.OrderByDescending(c => c.SelectedTime).ToList();
                    break;
                default:
                    classmodel = classmodel.OrderBy(c => c.SelectedTime).ToList();
                    break;

            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(classmodel.ToPagedList(pageNumber, pageSize));
        }

        // GET: /CreateClass/Details/5
        public ActionResult Details(long id = 0)
        {
            ClassModel ClassModel = db.ClassModels.Include(c => c.Professor).Include(c => c.Room).Where(c => c.Id == id).Single();
            if (ClassModel == null)
            {
                return HttpNotFound();
            }
            return View(ClassModel);
        }

        // GET: /CreateClass/Create
        public ActionResult Create()
        {
            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name");
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name");

            ClassModel classmodel = new ClassModel();
            classmodel.Time = this.PopulateTime().ToList().Select(time => new SelectListItem { Value = time, Text = time });

            return View(classmodel);
        }

        // POST: /CreateClass/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClassModel classmodel)
        {
            if (ModelState.IsValid)
            {
                db.ClassModels.Add(classmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name", classmodel.ProfessorId);
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name", classmodel.RoomId);
            return View(classmodel);
        }

        // GET: /CreateClass/CreateBatch
        public ActionResult Batch()
        {
            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name");
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name");

            CreateClassModel createclassmodel = new CreateClassModel();
            createclassmodel.Time = this.PopulateTime().ToList().Select(time => new SelectListItem { Value = time, Text = time });

            return View(createclassmodel);
        }

        // POST: /CreateClass/CreateBatch
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Batch(CreateClassModel createclassmodel)
        {
            if (ModelState.IsValid)
            {
                List<ClassModel> listclassmodel = this.CreateClasses(createclassmodel);
                foreach (ClassModel classmodel in listclassmodel)
                {
                    db.ClassModels.Add(classmodel);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name", createclassmodel.ProfessorId);
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name", createclassmodel.RoomId);
            return View(createclassmodel);
        }

        // GET: /CreateClass/Edit/5
        public ActionResult Edit(long id = 0)
        {
            ClassModel classmodel = db.ClassModels.Find(id);

            if (classmodel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name", classmodel.ProfessorId);
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name", classmodel.RoomId);

            classmodel.Time = this.PopulateTime().ToList().Select(time => new SelectListItem { Value = time, Text = time });

            return View(classmodel);
        }

        // POST: /CreateClass/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClassModel classmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(classmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProfessorId = new SelectList(db.ProfessorModels, "Id", "Name", classmodel.ProfessorId);
            ViewBag.RoomId = new SelectList(db.RoomModels, "Id", "Name", classmodel.RoomId);
            return View(classmodel);
        }

        // GET: /CreateClass/Delete/5
        public ActionResult Delete(long id = 0)
        {
            ClassModel classmodel = db.ClassModels.Find(id);
            classmodel.Professor = db.ProfessorModels.Find(classmodel.ProfessorId);
            classmodel.Room = db.RoomModels.Find(classmodel.RoomId);
            if (classmodel == null)
            {
                return HttpNotFound();
            }
            return View(classmodel);
        }

        // POST: /CreateClass/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ClassModel classmodel = db.ClassModels.Find(id);
            if (classmodel.Students.Count != 0 || classmodel.HaveAnyPresenceList())
                classmodel.Active = false;
            else
                db.ClassModels.Remove(classmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public List<string> PopulateTime()
        {
            //Set the Start Time Value
            DateTime start = DateTime.ParseExact("07:00", "HH:mm", null);
            //Set the End Time Value
            DateTime end = DateTime.ParseExact("21:00", "HH:mm", null);
            //Set the interval time 
            int interval = 15;
            //List to hold the values of intervals
            List<string> lstTimeIntervals = new List<string>();
            //Populate the list with 30 minutes interval values
            for (DateTime i = start; i <= end; i = i.AddMinutes(interval))
                lstTimeIntervals.Add(i.ToString("HH:mm"));
            return lstTimeIntervals;
        }

        public List<ClassModel> CreateClasses(CreateClassModel createclassmodel)
        {
            List<ClassModel> classes = new List<ClassModel>();
            ClassModel aula;
            DateTime start = DateTime.ParseExact(createclassmodel.FirstClass, "HH:mm", null);
            DateTime end = DateTime.ParseExact(createclassmodel.LastClass, "HH:mm", null);
            for (DateTime i = start; i <= end; i = i.AddMinutes(createclassmodel.Interval))
            {
                aula = new ClassModel();
                aula.Day = createclassmodel.Day;
                aula.Professor = createclassmodel.Professor;
                aula.ProfessorId = createclassmodel.ProfessorId;
                aula.Room = createclassmodel.Room;
                aula.RoomId = createclassmodel.RoomId;
                aula.SelectedTime = i.ToString("HH:mm");
                classes.Add(aula);
            }
            return classes;
        }

        public ActionResult FilterDayOfWeek(DayOfWeek dayOfWeek)
        {
            var classmodels = db.ClassModels.Include(c => c.Professor).Include(c => c.Room);

KaiutYoga/KaiutYoga/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaiutYoga.Models;

namespace KaiutYoga.Controllers
{
    [Authorize]
    public class RoomController : Controller
    {
        private KaiutYogaContext db = new KaiutYogaContext();

        //
        // GET: /Room/

        public ActionResult Index()
        {
            return View(db.RoomModels.ToList().OrderBy(c=>c.Name));
        }

        //
        // GET: /Room/Details/5

        public ActionResult Details(long id = 0)
        {
            RoomModel roommodel = db.RoomModels.Find(id);
            if (roommodel == null)
            {
                return HttpNotFound();
            }
            return View(roommodel);
        }

        //
        // GET: /Room/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Room/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomModel roommodel)
        {
            if (ModelState.IsValid)
            {
                db.RoomModels.Add(roommodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roommodel);
        }

        //
        // GET: /Room/Edit/5

        public ActionResult Edit(long id = 0)
        {
            RoomModel roommodel = db.RoomModels.Find(id);
            if (roommodel == null)
            {
                return HttpNotFound();
            }
            return View(roommodel);
        }

        //
        // POST: /Room/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomModel roommodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roommodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roommodel);
        }

        //
        // GET: /Room/Delete/5

        public ActionResult Delete(long id = 0)
        {
            RoomModel roommodel = db.RoomModels.Find(id);
            if (roommodel == null)
            {
                return HttpNotFound();
            }
            return View(roommodel);
        }

        //
        // POST: /Room/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                RoomModel roommodel = db.RoomModels.Find(id);
                db.RoomModels.Remove(roommodel);
                db.SaveChanges();
                ViewBag.ErrorContent = null;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorContent"]="Houve um problema ao apagar este registro, primeiro selecione outra sala para as aulas que são feitas nesta sala";
                return RedirectToAction("Index");
            }
}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

KaiutYoga/KaiutYoga/Views/Class/Batch.cshtml
@model KaiutYoga.Models.CreateClassModel

@{
    KaiutYoga.Models.KaiutYogaContext context = new KaiutYoga.Models.KaiutYogaContext();
    int amountProfessor = context.ProfessorModels.Count();
    int amountRoom = context.RoomModels.Count();

    ViewBag.Title = "Cadastro de série de aulas";
}

<h2>Aulas</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>Cadastro de série de aulas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ProfessorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProfessorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfessorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Day", new SelectList(Enum.GetValues(typeof(DayOfWeek))), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FirstClass", Model.Time, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Interval, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Interval, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Interval, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LastClass", Model.Time, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LastClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista de aulas", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<div class="modal fade" id="errorMsgModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title">Faltam dados!</h4>
            </div>
            <div class="modal-body">
                <p>Para criar um horário de aula voce ainda precisa de:</p>
                @if (amountProfessor == 0)
                {
                    <ul>@Html.ActionLink("Professor", "Create", "Professor", null, null)</ul>
                }
                @if (amountRoom == 0)
                {
                    <ul>@Html.ActionLink("Sala", "Create", "Room", null, null)</ul>
                }
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(document).ready(function () {
        @if (amountProfessor == 0 || amountRoom == 0) {
            <text>
            $('#errorMsgModal').modal('show');
            $('#errorMsgModal').on('hide.bs.modal', function(e) { return false; })
            </text>
        }
    })
</script>

KaiutYoga/KaiutYoga/Views/Class/Create.cshtml
@model KaiutYoga.Models.ClassModel

@{
    KaiutYoga.Models.KaiutYogaContext context = new KaiutYoga.Models.KaiutYogaContext();
    int amountProfessor = context.ProfessorModels.Count();
    int amountRoom = context.RoomModels.Count();

    ViewBag.Title = "Cadastro de aula";
}

<h2>Aulas</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div class="form-horizontal">
        <h4>Cadastro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ProfessorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProfessorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfessorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SelectedTime", Model.Time, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Day", new SelectList(Enum.GetValues(typeof(DayOfWeek))), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista de aulas", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<div class="modal fade" id="errorMsgModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title">Faltam dados!</h4>
            </div>
            <div class="modal-body">
                <p>Para criar um horário de aula voce ainda precisa de:</p>
                @if (amountProfessor == 0)
                {
                    <ul>@Html.ActionLink("Professor", "Create", "Professor", null, null)</ul>
                }
                @if (amountRoom == 0)
                {
                    <ul>@Html.ActionLink("Sala", "Create", "Room", null, null)</ul>
                }
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(document).ready(function () {
        @if (amountProfessor == 0 || amountRoom == 0) {
            <text>
            $('#errorMsgModal').modal('show');
            $('#errorMsgModal').on('hide.bs.modal', function(e) { return false; })
            </text>
        }
    })
</script>

KaiutYoga/KaiutYoga/Views/Class/Delete.cshtml
@model KaiutYoga.Models.ClassModel

@{
    ViewBag.Title = "Apagar aula";
}

<h2>Aulas</h2>

<div class="form-horizontal">
    <h4>Apagar</h4>
    <hr />
    <h3>Realmente deseja apagar este registro?</h3>

    <div class="form-group">
        @Html.LabelFor(model => model.Professor.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Professor.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Room.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Room.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SelectedTime, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
        </div>
    </div>
    @using (Html.BeginForm(null,null,FormMethod.Post, new { id = "deleteConfirm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (Model.Students.Count == 0 && !Model.HaveAnyPresenceList())
                {
                    <input type="submit" value="Apagar" class="btn btn-default" />
                }
                else
                {
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#confirmDeleteModal">Apagar</button>
                }
            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Voltar a lista de aulas", "Index")
</div>

<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Apagar aula de @Model.Day, @Model.SelectedTime</h4>
            </div>
            <div class="modal-body">
                <p>Esta aula possui alunos cadastrados ou alguma chamada feita.</p>
                <br />
                <p>Deseja continuar?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-danger" onclick="$('#deleteConfirm').submit();">Apagar!</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

KaiutYoga/KaiutYoga/Views/Class/Details.cshtml
@model KaiutYoga.Models.ClassModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ClassModel</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Professor.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Professor.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Room.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Room.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Day)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Day)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KaiutYoga/KaiutYoga/Views/Class/Index.cshtml
@model PagedList.IPagedList<KaiutYoga.Models.ClassModel>
@using PagedList.Mvc;


@{
    ViewBag.Title = "Lista de aulas";
}

<h2>Horário de aulas</h2>

<p>
    <div class="form-inline">
        <div class="form-group">
            @using (Html.BeginForm("Index", "Class", FormMethod.Get))
            {
                <select id="searchDayOfWeek" name="searchDayOfWeek" onchange="this.form.submit();" class="form-control">
                    <option value="">Dia da semana</option>
                    <option value="@DayOfWeek.Sunday">Domingo</option>
                    <option value="@DayOfWeek.Monday">Segunda-feira</option>
                    <option value="@DayOfWeek.Tuesday">Terça-feira</option>
                    <option value="@DayOfWeek.Wednesday">Quarta-feira</option>
                    <option value="@DayOfWeek.Thursday">Quinta-feira</option>
                    <option value="@DayOfWeek.Friday">Sexta-feira</option>
                    <option value="@DayOfWeek.Saturday">Sábado</option>
                </select>
            }
        </div>
        <button class="btn btn-primary" onclick="location.href='@Url.Action("Create")'"><i class="fa fa-plus" title="Editar aluno"></i> Novo registro</button>
        <button class="btn btn-info" onclick="location.href='@Url.Action("Batch")'"><i class="fa fa-plus" title="Editar aluno"></i> Lote de aulas</button>
    </div>
</p>
<script>
    $("#searchDayOfWeek").val("@ViewBag.CurrentFilter");
</script>
<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>
<div id="no-more-tables">
    <table class="table col-sm-12 table-striped table-condensed cf">
        <thead class="cf">
            <tr>
                <th>
                    @Html.ActionLink("Nome", "Index", new { sortOrder = ViewBag.ProfessorSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Sala", "Index", new { sortOrder = ViewBag.RoomSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Dia da semana", "Index", new { sortOrder = ViewBag.DaySortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Horário", "Index", new { sortOrder = ViewBag.TimeSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-title="Professor">
                        @Html.DisplayFor(modelItem => item.Professor.Name)
                    </td>
                    <td data-title="Sala">
                        @Html.DisplayFor(modelItem => item.Room.Name)
                    </td>
                    <td data-title="Dia da semana">
                        @{ string dayOfWeek = new System.Globalization.CultureInfo("pt-BR").DateTimeFormat.GetDayName(item.Day).ToString();}
                        @Html.DisplayFor(modelItem => dayOfWeek)
                    </td>
                    <td data-title="Horário">
                        @Html.DisplayFor(modelItem => item.SelectedTime)
                    </td>
                    <td data-title="" align="right">
                        <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete",new { id=item.Id})'"><i class="fa fa-trash" title="Apagar horário"></i> Apagar</button>
                        <button class="btn btn-warning btn-sm" onclick="location.href='@Url.Action("Edit", new { id = item.Id })'"><i class="fa fa-pencil" title="Editar horário"></i> Editar</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>